FROM node:24-alpine

ARG NODE_ENV="production"

WORKDIR /app
COPY . .

RUN corepack enable pnpm

RUN pnpm i --frozen-lockfile

RUN pnpm run build-only --mode ${NODE_ENV}

EXPOSE 4173

CMD ["sh", "-c", "pnpm run preview --host"]