FROM node:24-alpine

ARG NODE_ENV="production"
ARG VITE_API_ENDPOINT
ARG VITE_TURNSTILE_SITE_KEY
ARG VITE_RECOVERY

WORKDIR /app
COPY . .

RUN corepack enable pnpm

RUN pnpm i --frozen-lockfile

RUN echo "VITE_API_ENDPOINT=${VITE_API_ENDPOINT}" >> .env
RUN echo "VITE_TURNSTILE_SITE_KEY=${VITE_TURNSTILE_SITE_KEY}" >> .env
RUN echo "VITE_RECOVERY=${VITE_RECOVERY}" >> .env

RUN pnpm run build-only --mode ${NODE_ENV}

EXPOSE 4173

CMD ["sh", "-c", "pnpm run preview --host"]