FROM nginx

ARG server 'localhost:3000'
ARG room_name 'live'

WORKDIR /usr/share/nginx/html
COPY index.html .
COPY setup.sh .
COPY src ./src
COPY screen ./screen

RUN echo 'const config = {server: "'${server}'", room: "'${room_name}'"};' > /usr/share/nginx/html/src/js/config.js

EXPOSE 80
